#! /bin/sh

sxhkd &

killall -q polybar

polybar --reload lap &
polybar --reload monitor &

nitrogen --restore &

picom -f &

#open Funny Java Things
wmname LG3D

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           5
bspc config top_padding	        -5

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
